/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */
import type { RoomType } from './roomType';

export interface CreateRoomRequest {
  type?: RoomType;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  memberIds?: string[] | null;
}
