/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */
import type { FriendDto } from './friendDto';

export interface FriendDtoListResult {
  isSuccess?: boolean;
  /** @nullable */
  errorCode?: string | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: FriendDto[] | null;
}
