/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */

export type GetApiChatRoomsRoomIdMessagesParams = {
limit?: number;
before?: string;
};
