/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */

export interface LoginCommand {
  /** @nullable */
  emailOrUsername?: string | null;
  /** @nullable */
  password?: string | null;
}
