/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */
import type { MediaUploadResponse } from './mediaUploadResponse';

export interface MediaUploadResponseResult {
  isSuccess?: boolean;
  /** @nullable */
  errorCode?: string | null;
  /** @nullable */
  message?: string | null;
  data?: MediaUploadResponse;
}
