/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */

export interface MediaUploadResponse {
  /** @nullable */
  url?: string | null;
  /** @nullable */
  fileName?: string | null;
  size?: number;
}
