/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */

export type MessageType = typeof MessageType[keyof typeof MessageType];


export const MessageType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
