/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */

export type RoomRole = typeof RoomRole[keyof typeof RoomRole];


export const RoomRole = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
