/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */
import type { RoomRole } from './roomRole';

export interface RoomMemberDto {
  userId?: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  role?: RoomRole;
  joinedAt?: string;
  /** @nullable */
  lastReadAt?: string | null;
}
