/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */
import type { RoomMemberDto } from './roomMemberDto';
import type { RoomType } from './roomType';

export interface RoomDto {
  /** @nullable */
  id?: string | null;
  type?: RoomType;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  createdBy?: string;
  createdAt?: string;
  /** @nullable */
  members?: RoomMemberDto[] | null;
  unreadCount?: number;
  /** @nullable */
  lastMessage?: string | null;
  /** @nullable */
  lastMessageAt?: string | null;
}
