/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */

export type RoomType = typeof RoomType[keyof typeof RoomType];


export const RoomType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
