/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */

export interface UserDto {
  id?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  createdAt?: string;
}
