/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PulseChat.API
 * PulseChat REST API
 * OpenAPI spec version: v1
 */
import type { UserDto } from './userDto';

export interface UserDtoResult {
  isSuccess?: boolean;
  /** @nullable */
  errorCode?: string | null;
  /** @nullable */
  message?: string | null;
  data?: UserDto;
}
